### ISSUE TITLE
Task 7

### ISSUE THREAD

**Issue by a1ex7** [splincode/codework#1]
В 7-м задании почему просто не:

`input:focus {
    outline: solid 2px red;
}`

[http://htmlbook.ru/css/focus](url)

Без всяких сложных заморочек с JS (хотя по моему и там можно было проще сделать)

**Comment by splincode** [comment]
https://toster.ru/q/339979

Ну ваш ответ верен полностью с точки зрения производительности. Но вопрос был чисто в том, чтобы реализовать это правильно на JS.

**Comment by splincode** [comment]
Однако, я добавлю в ответ и вариант на css

**Comment by a1ex7** [comment]
Так и на JS это также несколькими строчками пишется, а не таким нагромождением

**Comment by splincode** [comment]
Очень здорово, было еще лучше если бы вы приложили JSFiddle, я бы опубликовал
